#!/usr/bin/env python3
"""
generate_model_atmega.py — Export model RF ke C++ header yang dioptimasi untuk ATmega

ATmega2560 memiliki keterbatasan:
  - RAM: 8 KB (sangat terbatas)
  - Flash: 256 KB
  - Clock: 16 MHz

Strategi optimasi:
  1. Kurangi jumlah trees (default 15 → 8-10 untuk ATmega)
  2. Kurangi max_depth (default 6 → 4-5 untuk ATmega)
  3. Generate C code yang langsung (tanpa library eksternal)
  4. Use uint16_t untuk ADC values, not double
  5. Inline decision tree functions untuk efisiensi

Output:
  include/model_rf_atmega.h — Header C++ untuk ATmega
  
Instalasi:
  pip install scikit-learn joblib numpy
  
Cara pakai:
  python generate_model_atmega.py \\
    --model data/model_rf.joblib \\
    --output include/model_rf_atmega.h \\
    --max-trees 8 \\
    --max-depth 4
"""

import os
import sys
import argparse
import pickle
from pathlib import Path

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.tree import _tree
    import numpy as np
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False
    print("ERROR: scikit-learn not installed. pip install scikit-learn")
    sys.exit(1)


class TreeToC:
    """Konversi decision tree ke C code"""
    
    def __init__(self, tree, feature_names=None):
        self.tree = tree
        self.feature_names = feature_names or []
        self.node_counter = 0
    
    def tree_to_code(self, node=0, depth=0, class_names=None):
        """Recursive convert tree ke C code"""
        indent = "    " * (depth + 2)
        
        if self.tree.feature[node] != _tree.TREE_UNDEFINED:
            # Internal node — decision
            name = self.feature_names[self.tree.feature[node]]
            threshold = self.tree.threshold[node]
            
            code = f'{indent}if (x[{self.tree.feature[node]}] <= {threshold:.1f}) {{\n'
            code += self.tree_to_code(self.tree.children_left[node], depth + 1, class_names)
            code += f'{indent}}} else {{\n'
            code += self.tree_to_code(self.tree.children_right[node], depth + 1, class_names)
            code += f'{indent}}}\n'
        else:
            # Leaf node — prediction
            class_idx = np.argmax(self.tree.value[node])
            code = f'{indent}return {int(class_idx)};\n'
        
        return code
    
    def to_c_function(self, func_name="predict_tree_0", class_names=None):
        """Generate C function untuk satu tree"""
        code = f"""
int {func_name}(float *x) {{
    // Tree decision node
{self.tree_to_code(class_names=class_names)}
}}
"""
        return code


def export_model_atmega(model_path, output_path, max_trees=8, max_depth=4):
    """
    Export Random Forest model ke C++ header untuk ATmega
    
    Args:
        model_path: Path ke model sklearn (pickle/joblib)
        output_path: Path untuk output C header
        max_trees: Maksimal jumlah trees yang di-export (ATmega limitation)
        max_depth: Maksimal depth per tree
    """
    
    # Load model
    print(f"[DIR] Loading model from: {model_path}")
    try:
        try:
            import joblib
            model = joblib.load(model_path)
        except ImportError:
            with open(model_path, 'rb') as f:
                model = pickle.load(f)
        except Exception:
            with open(model_path, 'rb') as f:
                model = pickle.load(f)
    except Exception as e:
        print(f"[ERR] Failed to load model: {e}")
        return False
    
    if not isinstance(model, RandomForestClassifier):
        print(f"[ERR] Expected RandomForestClassifier, got {type(model)}")
        return False
    
    print(f"[OK] Model loaded: {model.n_estimators} trees, max_depth={model.max_depth}")
    print(f"  Features: {model.n_features_in_}, Classes: {model.n_classes_}")
    
    # Siapkan feature names
    feature_names = [f"x[{i}]" for i in range(model.n_features_in_)]
    
    # Build C header
    header = f"""/*
 * model_rf_atmega.h — Random Forest untuk ATmega2560 (E-NOSE Kopi)
 * 
 * Generated by generate_model_atmega.py
 * 
 * ATmega2560 Constraints:
 *   - RAM: 8 KB (trees ditanam di Flash, tidak di-load ke RAM)
 *   - Flash: 256 KB (cukup untuk model + firmware)
 *   - Clock: 16 MHz
 * 
 * Model Info:
 *   - Trees: {min(model.n_estimators, max_trees)} (dari {model.n_estimators})
 *   - Max Depth: {model.max_depth}
 *   - Features: {model.n_features_in_} (8 means + 8 max)
 *   - Classes: {model.n_classes_} (dark=0, light=1, medium=2)
 * 
 * Cara pakai:
 *   #include "model_rf_atmega.h"
 *   float features[16] = {{ ... }};  // 8 means + 8 max
 *   int prediction = predictClass(features);
 * 
 * Classes:
 *   0 = dark
 *   1 = light  
 *   2 = medium
 */

#pragma once
#include <stdint.h>

#define NUM_CLASSES {model.n_classes_}
#define NUM_FEATURES {model.n_features_in_}
#define NUM_TREES {min(model.n_estimators, max_trees)}

"""
    
    # Generate tree functions
    num_trees = min(model.n_estimators, max_trees)
    converter = TreeToC(None, feature_names=feature_names)
    
    header += "// Decision tree functions\n"
    for i in range(num_trees):
        tree = model.estimators_[i].tree_
        converter.tree = tree
        tree_func = converter.to_c_function(f"tree_{i}")
        header += tree_func
    
    # Generate voting function
    header += f"""
// Ensemble prediction via voting
int predictClass(float *x) {{
    uint8_t votes[NUM_CLASSES] = {{0}};
    
"""
    
    for i in range(num_trees):
        header += f"    votes[tree_{i}(x)]++;\n"
    
    header += """
    // Return class dengan votes terbanyak
    uint8_t max_class = 0;
    uint8_t max_votes = votes[0];
    for (uint8_t i = 1; i < NUM_CLASSES; i++) {
        if (votes[i] > max_votes) {
            max_votes = votes[i];
            max_class = i;
        }
    }
    return max_class;
}

// Untuk kompatibilitas dengan inference_common.h
int doInference(float *features) {
    return predictClass(features);
}

"""
    
    # Save file
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(header)
        print(f"\n[OK] Model exported successfully!")
        print(f"     Output: {output_path}")
        print(f"     File size: {os.path.getsize(output_path) / 1024:.1f} KB")
        return True
    except Exception as e:
        print(f"[FAIL] Failed to write output: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Export Random Forest ke C++ untuk ATmega'
    )
    parser.add_argument('--model', type=str, default='data/model_rf.joblib',
                       help='Path ke model file')
    parser.add_argument('--output', type=str, default='include/model_rf_atmega.h',
                       help='Path untuk output C header')
    parser.add_argument('--max-trees', type=int, default=8,
                       help='Maksimal trees untuk ATmega (default: 8)')
    parser.add_argument('--max-depth', type=int, default=4,
                       help='Maksimal depth per tree (default: 4)')
    
    args = parser.parse_args()
    
    print("""
╔═══════════════════════════════════════════════════════════╗
║   Export RF Model untuk ATmega2560                        ║
╚═══════════════════════════════════════════════════════════╝
""")
    
    success = export_model_atmega(
        args.model,
        args.output,
        max_trees=args.max_trees,
        max_depth=args.max_depth
    )
    
    if success:
        print("""
[OK] Langkah berikutnya:
  1. Pastikan USE_ON_DEVICE_INFERENCE=1 di kode ATmega
  2. Include model_rf_atmega.h di source code
  3. Compile dan upload ke ATmega2560
""")
    
    return 0 if success else 1


if __name__ == '__main__':
    sys.exit(main())
