"""Tahap 7 — kontrak serial dan state tracker Pi (OFFLINE / READ-ONLY).

Versi firmware saat ini mengirim JSON per baris tanpa session_id/seq.
Adapter legacy membangkitkan envelope internal tanpa mengirim perintah
ke ATmega. Kontrak wire v1 bersifat spesifikasi untuk firmware MENDATANG.
Tidak membuka serial, port GPIO, COM5, SSH, atau mengendalikan aktuator.
Semua AI_TEST mengembalikan N/A sesuai Stage6 release gate.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import re
import sys
import uuid
from typing import Any, Callable

from acquisition_schema import ADC_COLS, is_sensor_payload
from stage6_release_gate import evaluate as stage6_decision

MAX_LINE_BYTES = 4096
MODES = {"ai_test", "labeled_data"}
PHASES = {"purging", "collecting"}
SESSION_RE = re.compile(r"^[a-zA-Z0-9_-]{8,64}$")
DEVICE_RE = re.compile(r"^[a-zA-Z0-9_-]{1,48}$")
FINAL_RESULTS = {"N/A", "UNKNOWN"}  # no roast predictions at this stage
ROOT = Path(__file__).resolve().parents[1]


class FrameError(ValueError):
    pass


def _no_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise FrameError("duplicate_json_key")
        result[key] = value
    return result


def decode_line(data: str | bytes) -> dict:
    try:
        raw = data.encode("utf-8") if isinstance(data, str) else data
        if len(raw) > MAX_LINE_BYTES or not raw or b"\x00" in raw:
            raise FrameError("line_size_or_nul_invalid")
        obj = json.loads(
            raw.decode("utf-8"), object_pairs_hook=_no_duplicate_keys,
            parse_constant=lambda _: (_ for _ in ()).throw(
                FrameError("nonfinite_json_number")
            ),
        )
        if not isinstance(obj, dict):
            raise FrameError("frame_not_object")
        return obj
    except (UnicodeError, json.JSONDecodeError, TypeError) as err:
        raise FrameError("invalid_json_or_encoding") from err


def validate_v1_envelope(obj: dict) -> dict:
    """Strict versioned transport proposal, NOT generated by current MCU."""
    allowed = {
        "version", "type", "device_id", "session_id", "message_seq",
        "emitted_uptime_ms", "mode", "payload",
    }
    if set(obj) != allowed:
        raise FrameError("v1_envelope_fields_invalid")
    if type(obj["version"]) is not int or obj["version"] != 1:
        raise FrameError("unsupported_protocol_version")
    if obj["type"] not in {
        "ACQ_START", "SENSOR_SAMPLE", "PHASE_CHANGE", "ACQ_PAUSE",
        "ACQ_RESUME", "ACQ_STOP", "ACQ_COMPLETE", "ACK", "NACK",
        "INFERENCE_REQUEST", "INFERENCE_RESULT", "INFERENCE_ERROR",
    }:
        raise FrameError("unknown_message_type")
    if not isinstance(obj["device_id"], str) or not DEVICE_RE.fullmatch(
        obj["device_id"]
    ):
        raise FrameError("invalid_device_id")
    if not isinstance(obj["session_id"], str) or not SESSION_RE.fullmatch(
        obj["session_id"]
    ):
        raise FrameError("invalid_session_id")
    if type(obj["message_seq"]) is not int or not (1 <= obj["message_seq"] <= 2**31-1):
        raise FrameError("invalid_message_seq")
    if type(obj["emitted_uptime_ms"]) is not int or not (
        0 <= obj["emitted_uptime_ms"] < 2**32
    ):
        raise FrameError("invalid_emitted_uptime")
    if obj["mode"] not in MODES or not isinstance(obj["payload"], dict):
        raise FrameError("invalid_mode_or_payload")
    if obj["mode"] == "ai_test" and any(
        key in obj["payload"] for key in
        ("sample_id", "origin", "origin_code", "roast_level", "label")
    ):
        raise FrameError("ai_test_label_leakage")
    if obj["type"] == "INFERENCE_RESULT":
        if obj["payload"].get("result") not in FINAL_RESULTS:
            raise FrameError("unvalidated_model_result_forbidden")
        if obj["payload"].get("confidence") is not None:
            raise FrameError("uncalibrated_confidence_forbidden")
    return obj


class V1SequenceGuard:
    """Reject replay/late/duplicate sequence. Does NOT send ACK to hardware."""

    def __init__(self):
        self.last: dict[tuple[str, str], tuple[int, int, str]] = {}
        self.completed: set[tuple[str, str]] = set()

    def accept(self, obj: dict) -> dict:
        obj = validate_v1_envelope(obj)
        key = obj["device_id"], obj["session_id"]
        seq, uptime = obj["message_seq"], obj["emitted_uptime_ms"]
        previous = self.last.get(key)
        if key in self.completed:
            raise FrameError("session_already_final")
        if previous is not None and (seq <= previous[0] or uptime < previous[1]):
            raise FrameError("duplicate_stale_or_out_of_order_v1")
        if previous is None and (seq != 1 or obj["type"] != "ACQ_START"):
            raise FrameError("v1_session_must_start_with_seq1")
        if previous is not None and previous[2] != obj["mode"]:
            raise FrameError("mode_changed_within_session")
        self.last[key] = seq, uptime, obj["mode"]
        if obj["type"] in {"ACQ_STOP", "ACQ_COMPLETE", "INFERENCE_ERROR"}:
            self.completed.add(key)
        return {
            "version": 1, "type": "ACK", "device_id": obj["device_id"],
            "session_id": obj["session_id"], "ack_seq": seq,
            "transmit_allowed": False,
            "note": "host_side_simulation_only_firmware_not_v1",
        }

    def simulate_receive(self, raw: str | bytes) -> dict:
        """ACK/NACK demonstration only. NEVER transmitted to actual MCU."""
        try:
            return self.accept(decode_line(raw))
        except FrameError as err:
            return {
                "version": 1, "type": "NACK", "reason": str(err),
                "transmit_allowed": False,
                "note": "host_side_simulation_only_firmware_not_v1",
            }


class LegacySessionBridge:
    """Passive state/quality tracker of actual firmware Serial 115200 output."""

    def __init__(self, session_factory: Callable[[], str] | None = None):
        self.session_factory = session_factory or (
            lambda: uuid.uuid4().hex
        )
        self.active: dict | None = None
        self.last_final: dict | None = None
        self.messages = 0
        self.events: list[dict] = []

    def emit(self, kind: str, **fields: Any) -> dict:
        self.messages += 1
        item = {"host_protocol": "legacy_adapter_v1", "host_seq": self.messages,
                "type": kind, **fields}
        self.events.append(item)
        return item

    def finish(self, reason: str, ok: bool = False) -> dict:
        s = self.active
        if s is None:
            return self.emit("IGNORED", reason="no_active_session")
        n = sum(s["counts"].values())
        result = self.emit(
            "SESSION_FINAL", session_id=s["id"], mode=s["mode"],
            status="N/A" if s["mode"] == "ai_test" else (
                "ACQUISITION_QA_ONLY" if ok else "INVALID"
            ),
            quality="COMPLETE_QA" if ok else "FAIL_CLOSED",
            reason=reason, sensor_samples=n, terminal=True,
            host_only=True, sent_to_atmega=False,
            actuator_commands_sent=0, model_invoked=False,
            nominal_150_samples=n == 150,
        )
        self.last_final = result
        self.active = None
        return result

    def abort(self, reason: str = "stream_disconnected") -> dict:
        return self.finish(reason, ok=False)

    def timeout_if_idle(self, *, elapsed_seconds: float,
                        limit_seconds: float = 10.0) -> dict | None:
        """Explicit host timer hook, testable without sleep/background thread.

        Caller supplies seconds since last valid frame; never sends a command
        to MCU or attempts to restart physical acquisition.
        """
        if not (0 < limit_seconds <= 120):
            raise ValueError("invalid_timeout_limit")
        if elapsed_seconds < 0:
            raise ValueError("invalid_elapsed_seconds")
        if self.active and elapsed_seconds >= limit_seconds:
            return self.finish("host_receive_timeout")
        return None

    @staticmethod
    def _validate_cycle_counts(session: dict) -> str | None:
        if session["paused"]:
            return "complete_while_paused"
        for cycle in range(1, 6):
            purge = session["counts"].get((cycle, "purging"), 0)
            collect = session["counts"].get((cycle, "collecting"), 0)
            if not (24 <= purge <= 26 and 4 <= collect <= 7):
                return f"missing_or_extra_cycle_{cycle}_phase_samples"
        return None

    def feed(self, raw: str | bytes) -> list[dict]:
        try:
            data = decode_line(raw)
        except FrameError as err:
            return [self.finish(str(err))] if self.active else [
                self.emit("DISCARDED", reason=str(err))
            ]
        event = data.get("event")
        if event == "ACQ_START":
            outputs = []
            if self.active:
                outputs.append(self.finish("new_start_preempted_incomplete"))
            mode = data.get("mode")
            if (mode not in MODES or
                    type(data.get("cycles_total")) is not int or
                    data["cycles_total"] != 5 or
                    data.get("purge_s") != 25 or
                    data.get("collect_s") != 5 or
                    data.get("phase") != "purging" or
                    data.get("cycle") != 1):
                outputs.append(self.emit("DISCARDED", reason="bad_start_contract"))
                return outputs
            if mode == "ai_test" and any(
                key in data for key in
                ("sample_id", "roast_level", "origin_code", "origin")
            ):
                outputs.append(self.emit("DISCARDED",
                                         reason="ai_test_label_leakage"))
                return outputs
            sid = self.session_factory()
            if not isinstance(sid, str) or not SESSION_RE.fullmatch(sid):
                raise FrameError("host_session_id_factory_invalid")
            self.active = {
                "id": sid, "mode": mode, "cycle": 1, "phase": "purging",
                "counts": {}, "last_uptime": -1, "paused": False,
                "duplicate": False,
            }
            outputs.append(self.emit("SESSION_STARTED", session_id=sid,
                                     mode=mode, legacy_no_device_session=True))
            return outputs
        if self.active is None:
            return [self.emit("IGNORED", reason="no_active_session")]
        s = self.active
        if is_sensor_payload(data):
            if s["paused"]:
                return [self.finish("sensor_during_pause")]
            cycle, phase = data["cycle"], data["phase"]
            if cycle != s["cycle"] or phase != s["phase"]:
                return [self.finish("out_of_order_cycle_or_phase")]
            name = (cycle, phase)
            current = s["counts"].get(name, 0)
            if data["sample_idx"] != current + 1:
                return [self.finish("duplicate_or_gapped_sample_idx")]
            # Legacy 'timestamp' is unsigned MCU uptime, not UTC.
            if data["timestamp"] <= s["last_uptime"]:
                return [self.finish("stale_or_duplicated_mcu_timestamp")]
            s["counts"][name] = current + 1
            s["last_uptime"] = data["timestamp"]
            return []
        if "phase" in data and "cycle" in data and event is None:
            return [self.finish("invalid_sensor_payload")]
        if event == "PHASE_CHANGE":
            cycle, phase = data.get("cycle"), data.get("phase")
            expected = ((s["cycle"], "collecting")
                        if s["phase"] == "purging" else
                        (s["cycle"] + 1, "purging"))
            if (cycle, phase) != expected or s["paused"]:
                return [self.finish("out_of_order_phase_change")]
            s["cycle"], s["phase"] = cycle, phase
            return []
        if event == "ACQ_PAUSE":
            if s["paused"]:
                return [self.finish("duplicate_pause")]
            s["paused"] = True
            return []
        if event == "ACQ_RESUME":
            if not s["paused"] or data.get("phase") != s["phase"]:
                return [self.finish("invalid_resume")]
            s["paused"] = False
            return []
        if event == "ACQ_STOP":
            return [self.finish("operator_stopped")]
        if event == "ACQ_COMPLETE":
            if data.get("cycles") != 5 or data.get("total_samples") != sum(
                s["counts"].values()
            ):
                return [self.finish("incorrect_acq_complete_counts")]
            issue = self._validate_cycle_counts(s)
            return [self.finish(issue or "five_cycles_checked_no_approved_model",
                                ok=issue is None)]
        # Preboot logs, I2C probe and on-device INFERENCE=N/A are diagnostic.
        if event == "INFERENCE" and data.get("result") not in ("N/A", None):
            return [self.finish("unsupported_ondevice_inference_result")]
        return []


def replay_csv(file: Path, *, session_factory: Callable[[], str] | None = None
               ) -> dict:
    """Use real, read-only CSV to generate firmware-shaped in-memory replay."""
    bridge = LegacySessionBridge(session_factory=session_factory)
    with file.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    if not rows:
        raise ValueError("empty_input_csv")
    if not all(c in rows[0] for c in
               ("timestamp", "run_id", "phase", "sample_idx", *ADC_COLS)):
        raise ValueError("not_canonical_mq3_csv")
    source_sha256 = hashlib.sha256(file.read_bytes()).hexdigest()
    bridge.feed(json.dumps({
        "event": "ACQ_START", "mode": "ai_test", "cycle": 1,
        "phase": "purging", "cycles_total": 5, "purge_s": 25,
        "collect_s": 5,
    }))
    previous = (1, "purging")
    count = 0
    for rec in rows:
        if not rec["sample_idx"]:
            continue  # event-only rows, not MCU SENSOR_SAMPLE
        cycle = int(rec["run_id"])
        phase = rec["phase"]
        if (cycle, phase) != previous:
            bridge.feed(json.dumps({
                "event": "PHASE_CHANGE", "cycle": cycle, "phase": phase,
            }))
            previous = (cycle, phase)
        data = {
            "timestamp": int(rec["timestamp"]),
            "cycle": cycle, "phase": phase,
            "sample_idx": int(rec["sample_idx"]),
        }
        data.update({channel: int(rec[channel]) for channel in ADC_COLS})
        bridge.feed(json.dumps(data))
        count += 1
    if bridge.active:
        bridge.feed(json.dumps({
            "event": "ACQ_COMPLETE", "cycles": 5, "total_samples": count,
        }))
    result = bridge.last_final or {
        "status": "N/A", "quality": "FAIL_CLOSED",
        "reason": "no_terminal_session",
    }
    return {
        "source_file_name": file.name,
        "source_sha256": source_sha256,
        "input_type": "historical_real_csv_replayed_as_ai_test_no_labels",
        "bridge": result,
        "note": "Offline replay only: no serial transport opened; not sent to MCU or Nextion",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--replay-csv", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    stage6 = stage6_decision()
    if stage6["model_promotion_allowed"]:
        raise RuntimeError("Stage7 must never promote a model")
    output = replay_csv(args.replay_csv)
    output["release_gate"] = stage6["status"]
    path = args.output.resolve()
    raw = (ROOT / "data/raw").resolve()
    if path == args.replay_csv.resolve() or path == raw or raw in path.parents:
        raise ValueError("Cannot overwrite input/raw CSV")
    if path.exists():
        raise FileExistsError("Do not overwrite replay output")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(output, indent=2, ensure_ascii=False)+"\n",
                    encoding="utf-8")
    print("STAGE7_LEGACY_REPLAY_PASS", output["bridge"]["quality"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
