"""train_rf_simple.py
Simple Random Forest training script for the smart-coffee project.

Usage:
  python scripts/train_rf_simple.py --file ../data/dataset_fitur.csv

The script:
- loads dataset CSV
- auto-detects feature columns (mean_ and max_ prefixes)
- encodes labels
- trains RandomForestClassifier
- prints evaluation metrics
- saves a model to models/rf_model.joblib
- optionally exports a C header via micromlgen with --export-header
"""
import argparse
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import joblib

try:
    from micromlgen import port
    HAS_MICROMLGEN = True
except Exception:
    HAS_MICROMLGEN = False


def main():
    p = argparse.ArgumentParser(description='Train a simple Random Forest on dataset_fitur.csv')
    p.add_argument('--file', '-f', default=os.path.join('..', 'data', 'dataset_fitur.csv'))
    p.add_argument('--n-estimators', type=int, default=15)
    p.add_argument('--max-depth', type=int, default=6)
    p.add_argument('--test-size', type=float, default=0.2)
    p.add_argument('--random-state', type=int, default=42)
    p.add_argument('--model-out', default=os.path.join('..', 'models', 'rf_model.joblib'))
    p.add_argument('--export-header', action='store_true', help='Export C header via micromlgen (include/model_rf.h)')
    args = p.parse_args()

    fp = os.path.abspath(args.file)
    if not os.path.exists(fp):
        print(f'File not found: {fp}')
        return

    df = pd.read_csv(fp)
    if 'label' not in df.columns:
        print('No label column found in CSV')
        return

    # Detect feature columns (mean_ or max_ prefixes)
    feature_cols = [c for c in df.columns if c.startswith('mean_') or c.startswith('max_')]
    if not feature_cols:
        print('No feature columns found (mean_*/max_*)')
        return

    X = df[feature_cols].values
    y = df['label'].values

    le = LabelEncoder()
    y_enc = le.fit_transform(y)

    # Split (if enough samples and >1 class)
    if len(df) >= 3 and len(set(y)) > 1:
        X_train, X_test, y_train, y_test = train_test_split(X, y_enc, test_size=args.test_size, stratify=y_enc, random_state=args.random_state)
    else:
        print('Warning: dataset small or single-class; training on all data')
        X_train, X_test, y_train, y_test = X, X, y_enc, y_enc

    clf = RandomForestClassifier(n_estimators=args.n_estimators, max_depth=args.max_depth, random_state=args.random_state)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {acc*100:.2f}%")
    print(classification_report(y_test, y_pred, zero_division=0))

    # Save model
    out_dir = os.path.abspath(os.path.dirname(args.model_out))
    os.makedirs(out_dir, exist_ok=True)
    joblib.dump({'model': clf, 'label_encoder': le, 'feature_cols': feature_cols}, args.model_out)
    print(f'Model saved to: {args.model_out}')

    # Optional export to C header
    if args.export_header:
        if not HAS_MICROMLGEN:
            print('micromlgen not installed; cannot export header. Install with pip install micromlgen')
        else:
            include_dir = os.path.join(os.path.dirname(os.path.dirname(fp)), 'include')
            os.makedirs(include_dir, exist_ok=True)
            try:
                c_code = port(clf, classmap={label: i for i, label in enumerate(le.classes_)})
            except TypeError:
                c_code = port(clf)
            header_path = os.path.join(include_dir, 'model_rf.h')
            with open(header_path, 'w', encoding='utf-8') as f:
                f.write('/* Generated by train_rf_simple.py */\n')
                f.write(c_code)
            print(f'Header exported to: {header_path}')


if __name__ == '__main__':
    main()
