/*
 * model_rf_atmega.h — Random Forest untuk ATmega2560 (E-NOSE Kopi)
 * 
 * Generated by generate_model_atmega.py
 * 
 * ATmega2560 Constraints:
 *   - RAM: 8 KB (trees ditanam di Flash, tidak di-load ke RAM)
 *   - Flash: 256 KB (cukup untuk model + firmware)
 *   - Clock: 16 MHz
 * 
 * Model Info:
 *   - Trees: 8 (dari 8)
 *   - Max Depth: 4
 *   - Features: 20 (8 means + 8 max)
 *   - Classes: 3 (dark=0, light=1, medium=2)
 * 
 * Cara pakai:
 *   #include "model_rf_atmega.h"
 *   float features[16] = { ... };  // 8 means + 8 max
 *   int prediction = predictClass(features);
 * 
 * Classes:
 *   0 = dark
 *   1 = light  
 *   2 = medium
 */

#pragma once
#include <stdint.h>

#define NUM_CLASSES 3
#define NUM_FEATURES 20
#define NUM_TREES 8

// Decision tree functions

int tree_0(float *x) {
    // Tree decision node
        if (x[6] <= 7065.2) {
            if (x[11] <= 2931.5) {
                return 1;
            } else {
                if (x[18] <= 14734.5) {
                    if (x[14] <= 10874.0) {
                        return 2;
                    } else {
                        return 0;
                    }
                } else {
                    return 1;
                }
            }
        } else {
            if (x[1] <= 2950.0) {
                if (x[18] <= 11897.0) {
                    return 2;
                } else {
                    if (x[18] <= 15979.0) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            } else {
                return 0;
            }
        }

}

int tree_1(float *x) {
    // Tree decision node
        if (x[6] <= 7065.2) {
            if (x[11] <= 2931.5) {
                return 1;
            } else {
                if (x[17] <= 17435.0) {
                    if (x[13] <= 10797.0) {
                        return 2;
                    } else {
                        return 0;
                    }
                } else {
                    return 1;
                }
            }
        } else {
            if (x[17] <= 10978.0) {
                return 2;
            } else {
                if (x[13] <= 11270.5) {
                    if (x[5] <= 2899.6) {
                        return 0;
                    } else {
                        return 0;
                    }
                } else {
                    return 2;
                }
            }
        }

}

int tree_2(float *x) {
    // Tree decision node
        if (x[17] <= 16539.0) {
            if (x[6] <= 8877.1) {
                if (x[0] <= 11248.6) {
                    if (x[4] <= 5547.3) {
                        return 1;
                    } else {
                        return 2;
                    }
                } else {
                    return 0;
                }
            } else {
                if (x[2] <= 2947.8) {
                    return 2;
                } else {
                    return 0;
                }
            }
        } else {
            if (x[14] <= 11652.5) {
                if (x[6] <= 7107.2) {
                    return 0;
                } else {
                    if (x[15] <= 2897.5) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            } else {
                if (x[6] <= 7324.6) {
                    if (x[13] <= 11523.0) {
                        return 1;
                    } else {
                        return 1;
                    }
                } else {
                    if (x[8] <= 16581.0) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            }
        }

}

int tree_3(float *x) {
    // Tree decision node
        if (x[6] <= 7065.2) {
            if (x[12] <= 2911.5) {
                return 1;
            } else {
                if (x[8] <= 13691.3) {
                    if (x[1] <= 2927.5) {
                        return 0;
                    } else {
                        return 2;
                    }
                } else {
                    return 1;
                }
            }
        } else {
            if (x[7] <= 16433.0) {
                if (x[19] <= 12938.0) {
                    return 0;
                } else {
                    return 2;
                }
            } else {
                if (x[16] <= 7534.5) {
                    return 2;
                } else {
                    return 0;
                }
            }
        }

}

int tree_4(float *x) {
    // Tree decision node
        if (x[9] <= 12677.9) {
            if (x[6] <= 7784.5) {
                return 1;
            } else {
                if (x[18] <= 10697.0) {
                    return 2;
                } else {
                    return 0;
                }
            }
        } else {
            if (x[3] <= 8000.6) {
                return 0;
            } else {
                if (x[15] <= 2949.0) {
                    if (x[16] <= 7197.0) {
                        return 0;
                    } else {
                        return 2;
                    }
                } else {
                    return 0;
                }
            }
        }

}

int tree_5(float *x) {
    // Tree decision node
        if (x[0] <= 15240.8) {
            if (x[4] <= 11320.5) {
                if (x[3] <= 9833.1) {
                    if (x[7] <= 6368.5) {
                        return 1;
                    } else {
                        return 2;
                    }
                } else {
                    if (x[9] <= 13869.5) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            } else {
                if (x[2] <= 2866.7) {
                    return 2;
                } else {
                    return 1;
                }
            }
        } else {
            if (x[4] <= 11092.7) {
                return 2;
            } else {
                return 0;
            }
        }

}

int tree_6(float *x) {
    // Tree decision node
        if (x[17] <= 16621.5) {
            if (x[16] <= 7251.5) {
                if (x[9] <= 12069.8) {
                    return 1;
                } else {
                    return 0;
                }
            } else {
                if (x[2] <= 2943.4) {
                    return 2;
                } else {
                    return 0;
                }
            }
        } else {
            if (x[9] <= 13059.1) {
                return 1;
            } else {
                if (x[4] <= 11040.0) {
                    if (x[2] <= 2892.7) {
                        return 0;
                    } else {
                        return 2;
                    }
                } else {
                    return 0;
                }
            }
        }

}

int tree_7(float *x) {
    // Tree decision node
        if (x[6] <= 7065.2) {
            if (x[4] <= 11528.9) {
                if (x[1] <= 2920.2) {
                    return 1;
                } else {
                    return 0;
                }
            } else {
                return 1;
            }
        } else {
            if (x[7] <= 10940.5) {
                return 2;
            } else {
                if (x[1] <= 2862.1) {
                    return 2;
                } else {
                    if (x[2] <= 2896.5) {
                        return 0;
                    } else {
                        return 0;
                    }
                }
            }
        }

}

// Ensemble prediction via voting
int predictClass(float *x) {
    uint8_t votes[NUM_CLASSES] = {0};
    
    votes[tree_0(x)]++;
    votes[tree_1(x)]++;
    votes[tree_2(x)]++;
    votes[tree_3(x)]++;
    votes[tree_4(x)]++;
    votes[tree_5(x)]++;
    votes[tree_6(x)]++;
    votes[tree_7(x)]++;

    // Return class dengan votes terbanyak
    uint8_t max_class = 0;
    uint8_t max_votes = votes[0];
    for (uint8_t i = 1; i < NUM_CLASSES; i++) {
        if (votes[i] > max_votes) {
            max_votes = votes[i];
            max_class = i;
        }
    }
    return max_class;
}

// Untuk kompatibilitas dengan inference_common.h
int doInference(float *features) {
    return predictClass(features);
}

