/*
 * model_rf_atmega.h — Random Forest untuk ATmega2560 (E-NOSE Kopi)
 * 
 * Generated by generate_model_atmega.py
 * 
 * ATmega2560 Constraints:
 *   - RAM: 8 KB (trees ditanam di Flash, tidak di-load ke RAM)
 *   - Flash: 256 KB (cukup untuk model + firmware)
 *   - Clock: 16 MHz
 * 
 * Model Info:
 *   - Trees: 12 (dari 12)
 *   - Max Depth: 5
 *   - Features: 89 (8 means + 8 max)
 *   - Classes: 3 (dark=0, light=1, medium=2)
 * 
 * Cara pakai:
 *   #include "model_rf_atmega.h"
 *   float features[16] = { ... };  // 8 means + 8 max
 *   int prediction = predictClass(features);
 * 
 * Classes:
 *   0 = dark
 *   1 = light  
 *   2 = medium
 */

#pragma once
#include <stdint.h>

#define NUM_CLASSES 3
#define NUM_FEATURES 89
#define NUM_TREES 12

// Decision tree functions

int tree_0(float *x) {
    // Tree decision node
        if (x[55] <= 0.1) {
            if (x[6] <= 7169.3) {
                if (x[77] <= -8.0) {
                    if (x[58] <= 34.5) {
                        return 1;
                    } else {
                        return 0;
                    }
                } else {
                    return 1;
                }
            } else {
                if (x[75] <= 0.1) {
                    if (x[6] <= 7431.8) {
                        return 2;
                    } else {
                        if (x[87] <= -12.4) {
                            return 0;
                        } else {
                            return 1;
                        }
                    }
                } else {
                    return 0;
                }
            }
        } else {
            if (x[25] <= 2.5) {
                return 0;
            } else {
                if (x[29] <= 345.3) {
                    return 1;
                } else {
                    return 0;
                }
            }
        }

}

int tree_1(float *x) {
    // Tree decision node
        if (x[13] <= 9663.5) {
            if (x[3] <= 7976.8) {
                if (x[85] <= -26.9) {
                    return 0;
                } else {
                    if (x[46] <= 5.8) {
                        return 1;
                    } else {
                        return 2;
                    }
                }
            } else {
                if (x[47] <= 4.0) {
                    return 1;
                } else {
                    return 2;
                }
            }
        } else {
            if (x[36] <= 0.5) {
                if (x[3] <= 10537.6) {
                    return 0;
                } else {
                    return 1;
                }
            } else {
                return 1;
            }
        }

}

int tree_2(float *x) {
    // Tree decision node
        if (x[83] <= -37.6) {
            if (x[26] <= 111.0) {
                return 0;
            } else {
                return 2;
            }
        } else {
            if (x[47] <= 4.1) {
                return 1;
            } else {
                if (x[56] <= -0.5) {
                    if (x[67] <= 66.2) {
                        return 2;
                    } else {
                        if (x[0] <= 13495.4) {
                            return 1;
                        } else {
                            return 0;
                        }
                    }
                } else {
                    if (x[41] <= 1.0) {
                        return 2;
                    } else {
                        if (x[45] <= 2.4) {
                            return 0;
                        } else {
                            return 1;
                        }
                    }
                }
            }
        }

}

int tree_3(float *x) {
    // Tree decision node
        if (x[48] <= 4.4) {
            if (x[45] <= 2.8) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (x[45] <= 2.5) {
                if (x[71] <= -0.2) {
                    return 0;
                } else {
                    return 1;
                }
            } else {
                if (x[81] <= -5.5) {
                    if (x[9] <= 13583.3) {
                        if (x[10] <= 17325.5) {
                            return 2;
                        } else {
                            return 1;
                        }
                    } else {
                        return 0;
                    }
                } else {
                    if (x[19] <= 40593.5) {
                        return 2;
                    } else {
                        return 1;
                    }
                }
            }
        }

}

int tree_4(float *x) {
    // Tree decision node
        if (x[0] <= 13449.6) {
            if (x[64] <= 17.5) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (x[55] <= 0.0) {
                if (x[19] <= 12842.0) {
                    return 1;
                } else {
                    if (x[29] <= 2199.8) {
                        if (x[11] <= 2894.0) {
                            return 1;
                        } else {
                            return 2;
                        }
                    } else {
                        return 1;
                    }
                }
            } else {
                if (x[5] <= 2912.1) {
                    return 0;
                } else {
                    if (x[14] <= 11931.5) {
                        if (x[21] <= 2.7) {
                            return 0;
                        } else {
                            return 2;
                        }
                    } else {
                        return 1;
                    }
                }
            }
        }

}

int tree_5(float *x) {
    // Tree decision node
        if (x[83] <= -35.1) {
            if (x[20] <= 1181.5) {
                if (x[57] <= -1.3) {
                    return 2;
                } else {
                    return 0;
                }
            } else {
                return 2;
            }
        } else {
            if (x[19] <= 13193.5) {
                return 1;
            } else {
                if (x[47] <= 6.1) {
                    if (x[17] <= 16055.0) {
                        return 1;
                    } else {
                        if (x[48] <= 4.6) {
                            return 0;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    return 1;
                }
            }
        }

}

int tree_6(float *x) {
    // Tree decision node
        if (x[43] <= 3.1) {
            return 1;
        } else {
            if (x[3] <= 9663.1) {
                if (x[61] <= 8.5) {
                    if (x[20] <= 3070.2) {
                        if (x[7] <= 14830.9) {
                            return 1;
                        } else {
                            return 2;
                        }
                    } else {
                        return 1;
                    }
                } else {
                    if (x[15] <= 2910.5) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            } else {
                if (x[4] <= 11528.9) {
                    return 0;
                } else {
                    if (x[6] <= 8110.6) {
                        return 1;
                    } else {
                        return 0;
                    }
                }
            }
        }

}

int tree_7(float *x) {
    // Tree decision node
        if (x[48] <= 4.6) {
            if (x[15] <= 2906.5) {
                if (x[62] <= 50.0) {
                    return 1;
                } else {
                    return 0;
                }
            } else {
                if (x[7] <= 16199.7) {
                    return 0;
                } else {
                    if (x[59] <= -0.0) {
                        return 0;
                    } else {
                        return 1;
                    }
                }
            }
        } else {
            if (x[18] <= 17908.5) {
                if (x[14] <= 11341.5) {
                    if (x[82] <= -4.5) {
                        if (x[72] <= -3.0) {
                            return 2;
                        } else {
                            return 0;
                        }
                    } else {
                        if (x[37] <= 0.0) {
                            return 2;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    return 0;
                }
            } else {
                return 1;
            }
        }

}

int tree_8(float *x) {
    // Tree decision node
        if (x[6] <= 7176.4) {
            if (x[23] <= 67.3) {
                if (x[48] <= 4.5) {
                    return 1;
                } else {
                    if (x[13] <= 9907.5) {
                        return 2;
                    } else {
                        return 0;
                    }
                }
            } else {
                return 0;
            }
        } else {
            if (x[55] <= 0.0) {
                if (x[1] <= 2890.7) {
                    return 1;
                } else {
                    if (x[4] <= 11152.6) {
                        return 2;
                    } else {
                        return 0;
                    }
                }
            } else {
                if (x[31] <= 0.0) {
                    return 0;
                } else {
                    return 2;
                }
            }
        }

}

int tree_9(float *x) {
    // Tree decision node
        if (x[48] <= 4.5) {
            if (x[11] <= 2960.5) {
                if (x[58] <= 31.0) {
                    return 1;
                } else {
                    return 0;
                }
            } else {
                return 0;
            }
        } else {
            if (x[43] <= 3.8) {
                if (x[33] <= 0.0) {
                    if (x[71] <= -0.2) {
                        return 2;
                    } else {
                        if (x[34] <= 0.0) {
                            return 1;
                        } else {
                            return 0;
                        }
                    }
                } else {
                    return 2;
                }
            } else {
                if (x[67] <= -32.7) {
                    return 1;
                } else {
                    return 0;
                }
            }
        }

}

int tree_10(float *x) {
    // Tree decision node
        if (x[5] <= 2948.9) {
            if (x[7] <= 15867.0) {
                if (x[44] <= 1.0) {
                    return 2;
                } else {
                    return 1;
                }
            } else {
                if (x[4] <= 10955.7) {
                    if (x[62] <= 30.0) {
                        return 2;
                    } else {
                        if (x[45] <= 2.5) {
                            return 0;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    if (x[13] <= 10583.0) {
                        return 0;
                    } else {
                        return 1;
                    }
                }
            }
        } else {
            return 0;
        }

}

int tree_11(float *x) {
    // Tree decision node
        if (x[12] <= 2944.0) {
            if (x[22] <= 3.6) {
                if (x[19] <= 12842.0) {
                    return 1;
                } else {
                    if (x[49] <= 289.8) {
                        if (x[42] <= 3.4) {
                            return 2;
                        } else {
                            return 1;
                        }
                    } else {
                        return 0;
                    }
                }
            } else {
                return 1;
            }
        } else {
            return 0;
        }

}

// Ensemble prediction via voting
int predictClass(float *x) {
    uint8_t votes[NUM_CLASSES] = {0};
    
    votes[tree_0(x)]++;
    votes[tree_1(x)]++;
    votes[tree_2(x)]++;
    votes[tree_3(x)]++;
    votes[tree_4(x)]++;
    votes[tree_5(x)]++;
    votes[tree_6(x)]++;
    votes[tree_7(x)]++;
    votes[tree_8(x)]++;
    votes[tree_9(x)]++;
    votes[tree_10(x)]++;
    votes[tree_11(x)]++;

    // Return class dengan votes terbanyak
    uint8_t max_class = 0;
    uint8_t max_votes = votes[0];
    for (uint8_t i = 1; i < NUM_CLASSES; i++) {
        if (votes[i] > max_votes) {
            max_votes = votes[i];
            max_class = i;
        }
    }
    return max_class;
}

// Untuk kompatibilitas dengan inference_common.h
int doInference(float *features) {
    return predictClass(features);
}

