/*
 * model_rf_atmega.h — Random Forest untuk ATmega2560 (E-NOSE Kopi)
 * 
 * Generated by generate_model_atmega.py
 * 
 * ATmega2560 Constraints:
 *   - RAM: 8 KB (trees ditanam di Flash, tidak di-load ke RAM)
 *   - Flash: 256 KB (cukup untuk model + firmware)
 *   - Clock: 16 MHz
 * 
 * Model Info:
 *   - Trees: 12 (dari 12)
 *   - Max Depth: 5
 *   - Features: 89 (8 means + 8 max)
 *   - Classes: 3 (dark=0, light=1, medium=2)
 * 
 * Cara pakai:
 *   #include "model_rf_atmega.h"
 *   float features[16] = { ... };  // 8 means + 8 max
 *   int prediction = predictClass(features);
 * 
 * Classes:
 *   0 = dark
 *   1 = light  
 *   2 = medium
 */

#pragma once
#include <stdint.h>

#define NUM_CLASSES 3
#define NUM_FEATURES 89
#define NUM_TREES 12

// Decision tree functions

int tree_0(float *x) {
    // Tree decision node
        if (x[8] <= 11005.8) {
            if (x[6] <= 7965.8) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (x[84] <= -14.0) {
                if (x[23] <= 62.5) {
                    return 0;
                } else {
                    if (x[57] <= -19.5) {
                        return 1;
                    } else {
                        return 2;
                    }
                }
            } else {
                if (x[6] <= 7178.7) {
                    if (x[52] <= -0.5) {
                        if (x[41] <= 1.0) {
                            return 2;
                        } else {
                            return 1;
                        }
                    } else {
                        return 0;
                    }
                } else {
                    if (x[19] <= 13396.0) {
                        return 1;
                    } else {
                        if (x[48] <= 5.0) {
                            return 2;
                        } else {
                            return 2;
                        }
                    }
                }
            }
        }

}

int tree_1(float *x) {
    // Tree decision node
        if (x[13] <= 9456.5) {
            if (x[3] <= 7726.8) {
                if (x[85] <= -28.1) {
                    return 0;
                } else {
                    if (x[46] <= 5.7) {
                        return 1;
                    } else {
                        return 2;
                    }
                }
            } else {
                return 2;
            }
        } else {
            if (x[66] <= 51.5) {
                if (x[1] <= 2958.9) {
                    if (x[67] <= 81.5) {
                        return 1;
                    } else {
                        return 0;
                    }
                } else {
                    return 0;
                }
            } else {
                return 0;
            }
        }

}

int tree_2(float *x) {
    // Tree decision node
        if (x[6] <= 7441.3) {
            if (x[75] <= -0.3) {
                return 2;
            } else {
                if (x[58] <= 31.0) {
                    if (x[8] <= 14739.5) {
                        if (x[0] <= 16156.0) {
                            return 1;
                        } else {
                            return 2;
                        }
                    } else {
                        return 2;
                    }
                } else {
                    if (x[0] <= 15270.6) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            }
        } else {
            if (x[78] <= -3.5) {
                return 0;
            } else {
                return 2;
            }
        }

}

int tree_3(float *x) {
    // Tree decision node
        if (x[48] <= 4.7) {
            if (x[45] <= 2.5) {
                if (x[60] <= -1.0) {
                    return 0;
                } else {
                    if (x[71] <= -0.2) {
                        return 0;
                    } else {
                        return 1;
                    }
                }
            } else {
                return 0;
            }
        } else {
            if (x[81] <= -5.9) {
                if (x[85] <= -114.5) {
                    return 2;
                } else {
                    return 0;
                }
            } else {
                if (x[11] <= 2894.0) {
                    return 1;
                } else {
                    if (x[57] <= -15.0) {
                        return 0;
                    } else {
                        return 2;
                    }
                }
            }
        }

}

int tree_4(float *x) {
    // Tree decision node
        if (x[0] <= 13355.2) {
            if (x[15] <= 2937.0) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (x[48] <= 4.6) {
                if (x[72] <= -1.5) {
                    if (x[55] <= -0.1) {
                        if (x[46] <= 5.6) {
                            return 2;
                        } else {
                            return 1;
                        }
                    } else {
                        return 0;
                    }
                } else {
                    if (x[46] <= 4.8) {
                        return 0;
                    } else {
                        return 1;
                    }
                }
            } else {
                if (x[14] <= 11376.5) {
                    if (x[43] <= 3.4) {
                        return 0;
                    } else {
                        if (x[46] <= 5.5) {
                            return 1;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    if (x[38] <= 0.3) {
                        return 0;
                    } else {
                        if (x[63] <= 62.7) {
                            return 1;
                        } else {
                            return 2;
                        }
                    }
                }
            }
        }

}

int tree_5(float *x) {
    // Tree decision node
        if (x[61] <= 16.4) {
            if (x[9] <= 12536.6) {
                return 1;
            } else {
                if (x[13] <= 9922.5) {
                    if (x[55] <= 0.1) {
                        if (x[45] <= 2.6) {
                            return 2;
                        } else {
                            return 2;
                        }
                    } else {
                        if (x[61] <= 3.9) {
                            return 2;
                        } else {
                            return 0;
                        }
                    }
                } else {
                    if (x[17] <= 16736.0) {
                        return 0;
                    } else {
                        return 1;
                    }
                }
            }
        } else {
            if (x[6] <= 7350.1) {
                return 2;
            } else {
                return 0;
            }
        }

}

int tree_6(float *x) {
    // Tree decision node
        if (x[43] <= 3.1) {
            return 1;
        } else {
            if (x[3] <= 9663.1) {
                if (x[19] <= 16629.5) {
                    if (x[84] <= -90.5) {
                        if (x[74] <= -2.5) {
                            return 2;
                        } else {
                            return 0;
                        }
                    } else {
                        if (x[10] <= 14425.0) {
                            return 1;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    return 1;
                }
            } else {
                if (x[4] <= 11232.2) {
                    return 0;
                } else {
                    if (x[6] <= 8052.2) {
                        return 1;
                    } else {
                        return 0;
                    }
                }
            }
        }

}

int tree_7(float *x) {
    // Tree decision node
        if (x[19] <= 12627.5) {
            if (x[63] <= 72.7) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (x[11] <= 2894.0) {
                return 1;
            } else {
                if (x[23] <= 30.8) {
                    if (x[31] <= 0.0) {
                        return 2;
                    } else {
                        if (x[32] <= 0.0) {
                            return 0;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    if (x[14] <= 11876.5) {
                        return 2;
                    } else {
                        if (x[4] <= 12771.4) {
                            return 0;
                        } else {
                            return 1;
                        }
                    }
                }
            }
        }

}

int tree_8(float *x) {
    // Tree decision node
        if (x[6] <= 7466.2) {
            if (x[8] <= 11829.3) {
                return 1;
            } else {
                if (x[48] <= 4.7) {
                    if (x[13] <= 10578.5) {
                        return 0;
                    } else {
                        return 1;
                    }
                } else {
                    if (x[55] <= 0.0) {
                        if (x[30] <= 0.6) {
                            return 2;
                        } else {
                            return 1;
                        }
                    } else {
                        if (x[71] <= -0.2) {
                            return 2;
                        } else {
                            return 0;
                        }
                    }
                }
            }
        } else {
            if (x[34] <= 0.0) {
                return 2;
            } else {
                return 0;
            }
        }

}

int tree_9(float *x) {
    // Tree decision node
        if (x[22] <= 2.6) {
            if (x[62] <= 4.5) {
                if (x[16] <= 7257.5) {
                    if (x[58] <= -24.5) {
                        return 2;
                    } else {
                        return 1;
                    }
                } else {
                    if (x[32] <= 0.0) {
                        if (x[44] <= 1.0) {
                            return 2;
                        } else {
                            return 2;
                        }
                    } else {
                        if (x[16] <= 7482.0) {
                            return 2;
                        } else {
                            return 0;
                        }
                    }
                }
            } else {
                if (x[42] <= 3.6) {
                    if (x[76] <= -2.5) {
                        return 2;
                    } else {
                        return 0;
                    }
                } else {
                    return 1;
                }
            }
        } else {
            return 1;
        }

}

int tree_10(float *x) {
    // Tree decision node
        if (x[5] <= 2941.1) {
            if (x[7] <= 15836.0) {
                if (x[44] <= 1.0) {
                    if (x[58] <= 62.0) {
                        return 0;
                    } else {
                        return 1;
                    }
                } else {
                    return 1;
                }
            } else {
                if (x[14] <= 11807.0) {
                    if (x[81] <= -4.6) {
                        if (x[75] <= -0.3) {
                            return 2;
                        } else {
                            return 0;
                        }
                    } else {
                        if (x[78] <= -0.5) {
                            return 0;
                        } else {
                            return 2;
                        }
                    }
                } else {
                    if (x[17] <= 19145.0) {
                        return 1;
                    } else {
                        return 0;
                    }
                }
            }
        } else {
            return 0;
        }

}

int tree_11(float *x) {
    // Tree decision node
        if (x[12] <= 2947.0) {
            if (x[30] <= 0.1) {
                if (x[19] <= 13405.5) {
                    return 1;
                } else {
                    if (x[12] <= 2880.0) {
                        return 2;
                    } else {
                        return 1;
                    }
                }
            } else {
                if (x[14] <= 11578.5) {
                    if (x[23] <= 26.4) {
                        if (x[4] <= 10491.7) {
                            return 2;
                        } else {
                            return 0;
                        }
                    } else {
                        if (x[45] <= 2.8) {
                            return 2;
                        } else {
                            return 0;
                        }
                    }
                } else {
                    if (x[49] <= 377.9) {
                        return 1;
                    } else {
                        return 0;
                    }
                }
            }
        } else {
            return 0;
        }

}

// Ensemble prediction via voting
int predictClass(float *x) {
    uint8_t votes[NUM_CLASSES] = {0};
    
    votes[tree_0(x)]++;
    votes[tree_1(x)]++;
    votes[tree_2(x)]++;
    votes[tree_3(x)]++;
    votes[tree_4(x)]++;
    votes[tree_5(x)]++;
    votes[tree_6(x)]++;
    votes[tree_7(x)]++;
    votes[tree_8(x)]++;
    votes[tree_9(x)]++;
    votes[tree_10(x)]++;
    votes[tree_11(x)]++;

    // Return class dengan votes terbanyak
    uint8_t max_class = 0;
    uint8_t max_votes = votes[0];
    for (uint8_t i = 1; i < NUM_CLASSES; i++) {
        if (votes[i] > max_votes) {
            max_votes = votes[i];
            max_class = i;
        }
    }
    return max_class;
}

// Untuk kompatibilitas dengan inference_common.h
int doInference(float *features) {
    return predictClass(features);
}

